# Generated by Django 3.1.7 on 2021-09-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Keyword')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Business Name')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Business/Profile/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=1200, verbose_name='Description')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='Website')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('status', models.CharField(default='unverified', max_length=50, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.category')),
            ],
        ),
    ]
