# Generated by Django 3.1.7 on 2021-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='Langauge'),
        ),
    ]
