# Generated by Django 3.1.7 on 2021-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
