# Generated by Django 3.1.7 on 2021-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm_email',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
    ]
