# Generated by Django 3.1.7 on 2021-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20211004_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='Image/Settings/ProfileImages/dummy.png', max_length=500, upload_to='Image/Settings/ProfileImages', verbose_name='Profile Image'),
        ),
    ]
