# Generated by Django 3.1.7 on 2021-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20211011_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=100, verbose_name='SMTP SERVER')),
                ('port', models.IntegerField(default=587, verbose_name='Port')),
                ('email', models.CharField(default='malonetechnologies101.com', max_length=100, verbose_name='App Email')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
    ]
