# Generated by Django 3.1.7 on 2021-10-21 13:22

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_emailapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(default='dummy.png', max_length=500, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Image/Business/Profile/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='Image/Settings/ProfileImages/dummy.png', max_length=500, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Image/Settings/ProfileImages', verbose_name='Profile Image'),
        ),
    ]
